displayName: JWT AntPath
summary: JWT Verification exclude the configured path for Traefik 2.x
type: middleware
import: github.com/x-ream/traefik-plugin-jwt-antpath
compatibility: TODO
testData:
  HeaderKey: "Authorization"
  SecureKey:  "my-secure-key"
  Paths:
    - "/foo/**"
